### ISSUE TITLE
Grant writing training day

### ISSUE THREAD

**Issue by EKaroune** [aim-rsf/AIM-ECR-network#47]
Preparation for grant writing online training day

```[tasklist]
### Tasks
- [ ] Start hackmd to plan out day and resources
- [ ] Speak to Emmy B about speakers and resources
- [ ] Find speakers/trainers
- [ ] Get costings for trainers
- [ ] Find possible date - advertise/ask ECR network about a few possible dates in June.
- [ ] Confirm schedule and speakers
- [ ] Set up zoom registration
- [ ] Advertise to ECR network and to Turing ECR network by email and slack - link to zoom registration
- [ ] Run workshop
- [ ] Get feedback
- [ ] Archive resources
```

**Comment by EKaroune** [comment]
Planning hackmd is here - https://hackmd.io/@d6CiydavSD6KFFgSIBMlGg/rJ1kSLBbC

**Comment by EKaroune** [comment]
tagging you here just for awareness @BatoolMM - no actions for you.

**Comment by BatoolMM** [comment]
Thank you @EKaroune - let em know if I can help with anything or if you want me to attend any of the meetings with the instructors.
