### ISSUE TITLE
Creating Guidelines around Hotels and transport reimbursement 

### ISSUE THREAD

**Issue by BatoolMM** [aim-rsf/AIM-ECR-network#6]
We need to find ways which minimise the need for ECRs to spend from their own pocket.

```[tasklist]
### Tasks
- [x] Ask the PMU about a bursary system where attendees are granted a fixed amount that they can flexibly use for both accommodation and travel
- [x] Ask other Turing Programmes/DSG about the system they use
- [x] Discuss the options with TPS PM
- [x] Create guidelines around the Hotels and transport reimbursement
- [ ] Circulate these guidelines with PMs from all seven RCs, maybe present them and discuss them in the regular PMs meeting
- [ ] Document all the learnings and share it with other programmes
```

**Comment by BatoolMM** [comment]
@eirini-zormpa I confirmed the new way of paying for the hotels directly. The process is documented [here](https://hackmd.io/cmI-rXf-QteHTvAWsdH87w). I included it in HackMD as it includes sensitive information.

The only problem with this method is that we need to know the number of rooms we needed at least 7 weeks before the event.

**Comment by eirini-zormpa** [comment]
So we need to know numbers by early October - I better get that registration form out quick :joy:
The HackMD is restricted - is there a way to share it only with me? I only know how to share with all signed in users 🤔

**Comment by BatoolMM** [comment]
Re-added you - you should have access to it now!

**Comment by eirini-zormpa** [comment]
yeeees thank you!
